import '#assets/styles/app.css'

import { inter } from '#assets/fonts'
import { setTheme } from '#utils'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout(props: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: <explanation> */}
        <script dangerouslySetInnerHTML={{ __html: `(${setTheme})();` }} />
      </head>
      <body className={`${inter.className} antialiased flex`}>
        {props.children}
      </body>
    </html>
  )
}
